# -*- coding: utf-8 -*-
"""Baixar vídeos do youtube usando python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PfevnB3prn4Qwf8kJQHxOvez02nmP4Ex
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pytube
# %pip install shell
# %pip install --upgrade pytube

from pytube import YouTube

#Para perguntar o link onde será retirado o vídeo 
link = input("Entre com o link do Youtube que você deseja baixar:  ")
yt = YouTube(link)

#Apresentar detalhes do vídeo
print("Título: ",yt.title)
print("Número de visualizações: ",yt.views)
print("Tamanho do vídeo: ",yt.length)
print("Rating do vídeo: ",yt.rating)
print(yt.thumbnail_url)
#Pegando a melhor resolução do vídeo
ys = yt.streams.get_highest_resolution()

#Iniciando o download
print("Baixando...")
ys.download()
print("Processamento finalizado!!")